name: Quality Check

on: [pull_request]

jobs:
  check_code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"  # lower bound of the supported Python versions
      - uses: pre-commit/action@v3.0.1
